### ISSUE TITLE
smoker error

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#120]
```
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Integer, Data: [Pair{Type|Unsigned Byte, 11}, Pair{Type|String, minecraft:furnace}, Pair{Type|String, {"text":"Smoker"}}, Pair{Type|Unsigned Byte, 3}], Source 0: com.github.creeper123123321.viaaas.protocol.id47toid5.packets.InventoryPacketsKt$registerInventoryPackets$1$registerMap$1 (Anonymous), Packet ID: 45, Source 1: com.github.creeper123123321.viaaas.protocol.id47toid5.packets.InventoryPacketsKt$registerInventoryPackets$1 (Anonymous)}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(4) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[viaaas-master.jar:?]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.type.types.IntType.read(IntType.java:36) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.type.types.IntType.read(IntType.java:29) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:167) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:219) ~[viaaas-master.jar:?]
	at com.github.creeper123123321.viaaas.protocol.id47toid5.packets.InventoryPacketsKt$registerInventoryPackets$1$registerMap$1.handle(InventoryPackets.kt:34) ~[viaaas-master.jar:?]
```

**Comment by FlorianMichael** [comment]
VIAaaS now uses ViaLegacy for 1.8 -> 1.7
