### ISSUE TITLE
error

### ISSUE THREAD

**Issue by killme990** [ViaVersion/VIAaaS#151]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/viaversion/aas/VIAaaSKt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
meliss

**Comment by tomcraft** [comment]
You need at least Java 11 to run VIAaaS

**Comment by Camotoy** [comment]
https://adoptopenjdk.net/ if you need a download link.

**Comment by killme990** [comment]
do i need wss or does it come with a websocket client ?

**Comment by killme990** [comment]
ok i tried it i downloaded java hotspot 11 lts mac and it says unknown hostname in my minecraft im probbably doing something obvious also if you get it to work how do i get it to work for other computers on the same network

**Comment by Camotoy** [comment]
For help with setting up, you should join ViaVersion's Discord: https://discord.gg/viaversion

**Comment by killme990** [comment]
pice of fucking shit
fuck you all THANKS FOR NOTHING
